# Generated by Django 5.0.6 on 2024-07-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maruegg", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("part", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("모집요강", "모집요강"), ("입시결과", "입시결과"), ("기출문제", "기출문제")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("part", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("모집요강", "모집요강"), ("입시결과", "입시결과"), ("기출문제", "기출문제")],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[("모집요강", "모집요강"), ("입시결과", "입시결과"), ("기출문제", "기출문제")],
                default="모집요강",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
