# Generated by Django 5.0.6 on 2024-07-12 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maruegg", "0002_document2_document3_document_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Document",
            new_name="Document1",
        ),
    ]
