# Generated by Django 5.0.6 on 2024-07-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maruegg", "0003_rename_document_document1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document1",
            name="category",
            field=models.CharField(
                choices=[
                    ("모집요강", "모집요강"),
                    ("입시결과", "입시결과"),
                    ("기출문제", "기출문제"),
                    ("대학생활", "대학생활"),
                    ("면접/실기", "면접/실기"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document2",
            name="category",
            field=models.CharField(
                choices=[
                    ("모집요강", "모집요강"),
                    ("입시결과", "입시결과"),
                    ("기출문제", "기출문제"),
                    ("대학생활", "대학생활"),
                    ("면접/실기", "면접/실기"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document3",
            name="category",
            field=models.CharField(
                choices=[
                    ("모집요강", "모집요강"),
                    ("입시결과", "입시결과"),
                    ("기출문제", "기출문제"),
                    ("대학생활", "대학생활"),
                    ("면접/실기", "면접/실기"),
                ],
                max_length=20,
            ),
        ),
    ]
