# Generated by Django 5.0.6 on 2024-07-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maruegg", "0004_alter_document1_category_alter_document2_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document1",
            name="page",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="document2",
            name="page",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="document3",
            name="page",
            field=models.IntegerField(default=1),
        ),
    ]
