# Generated by Django 5.0.6 on 2024-07-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maruegg", "0005_document1_page_document2_page_document3_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document1",
            name="part",
        ),
        migrations.RemoveField(
            model_name="document2",
            name="part",
        ),
        migrations.RemoveField(
            model_name="document3",
            name="part",
        ),
    ]
