# Generated by Django 5.0.6 on 2024-11-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maruegg", "0006_remove_document1_part_remove_document2_part_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document1",
            name="category",
            field=models.CharField(
                choices=[
                    ("모집요강", "모집요강"),
                    ("입시결과", "입시결과"),
                    ("기출문제", "기출문제"),
                    ("면접/실기", "면접/실기"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document2",
            name="category",
            field=models.CharField(
                choices=[
                    ("모집요강", "모집요강"),
                    ("입시결과", "입시결과"),
                    ("기출문제", "기출문제"),
                    ("면접/실기", "면접/실기"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document3",
            name="category",
            field=models.CharField(
                choices=[
                    ("모집요강", "모집요강"),
                    ("입시결과", "입시결과"),
                    ("기출문제", "기출문제"),
                    ("면접/실기", "면접/실기"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_type", models.CharField(max_length=50)),
                ("question_category", models.CharField(max_length=50)),
                ("prompt_text", models.TextField()),
            ],
            options={
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompts",
                "unique_together": {("question_type", "question_category")},
            },
        ),
    ]
