# Generated by Django 4.2.6 on 2025-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maruegg", "0007_alter_document1_category_alter_document2_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableOfContents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "toc_type",
                    models.CharField(
                        choices=[
                            ("수시", "수시"),
                            ("정시", "정시"),
                            ("편입학", "편입학"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "toc_category",
                    models.CharField(
                        choices=[
                            ("모집요강", "모집요강"),
                            ("입시결과", "입시결과"),
                            ("기출문제", "기출문제"),
                            ("대학생활", "대학생활"),
                            ("면접/실기", "면접/실기"),
                        ],
                        max_length=20,
                    ),
                ),
                ("toc_text", models.TextField()),
            ],
            options={
                "verbose_name": "Table of Contents",
                "verbose_name_plural": "Table of Contents",
                "unique_together": {("toc_type", "toc_category")},
            },
        ),
    ]
